# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: ltsc2019
    image: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

stages:
  - stage: stage1
    pool:
      vmImage: 'windows-2019'

    jobs:
      - job: Job1
        displayName: Host Job 1

        steps:
        - task: PowerShell@2
          displayName: Host Step 1
          target: host
          inputs:
            targetType: 'inline'
            script: |
              docker ps
              docker images
              $PSVersionTable
              Get-ComputerInfo
            pwsh: true

        - task: PowerShell@2
          displayName: Container Step 1
          target: 
            container: ltsc2019
          inputs:
            targetType: 'inline'
            script: |
              $PSVersionTable
              Get-ComputerInfo

        - task: PowerShell@2
          displayName: Host Step 2
          target: host
          inputs:
            targetType: 'inline'
            script: 'docker ps'
            pwsh: true

        - task: PowerShell@2
          displayName: Container Step 2
          target:
            container: ltsc2019
          inputs:
            targetType: 'inline'
            script: |
              $PSVersionTable
              Get-ComputerInfo
