# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: stage1
    pool:
      vmImage: 'windows-2019'

    jobs:
      - job: Job1
        displayName: Host Job 1

        steps:
        - task: PowerShell@2
          displayName: Host Step 1
          target: host
          inputs:
            targetType: 'inline'
            script: |
              docker ps
              docker images
              docker pull mcr.microsoft.com/windows/servercore:ltsc2019
              $PSVersionTable
              Get-ComputerInfo
            pwsh: true
